<?xml version="1.0"?>
<robot name="robotic_arm" xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="base_width" value="0.05" />
    <xacro:property name="base_length" value="0.05" />
    <xacro:property name="base_heigth" value="1.0" />
    <xacro:property name="axle_offset" value="0.5" />

    <link name="left_gripper_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.015 0.12" />
            </geometry>
            <material name = "black" />
        </visual>
        <collision>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
            <geometry>
                <box size="0.1 0.015 0.12" />
            </geometry>
        </collision>
        <xacro:default_inertial z_value="0" i_value="1e-6" mass="1"/>

    </link>


    <joint name="left_to_top_joint" type="revolute">
        <parent link="top_link"/>
        <child link="left_gripper_link"/>
        <origin xyz="0 -${base_width} ${base_heigth - axle_offset}" rpy="0 -1.57 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="30.0" lower="-0.548" upper="0.0" velocity="0.1"/>
    </joint>


    <link name="right_gripper_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.1 0.015 0.12" />
            </geometry>
            <material name = "black" />

        </visual>
        <collision>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
            <geometry>
                <box size="0.1 0.015 0.12" />
            </geometry>
        </collision>
        <xacro:default_inertial z_value="0" i_value="1e-6" mass="1"/>
    </link> 

  
    
    <joint name="right_to_top_joint" type="revolute">
        <parent link="top_link"/>
        <child link="right_gripper_link"/>
        <origin xyz="0 ${base_width} ${base_heigth - axle_offset}" rpy="0 -1.57 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="30.0" lower="-0.548" upper="0.0" velocity="0.1"/>
    </joint>




 
</robot>
