<?xml version="1.0"?>
<robot name="robotic_arm" xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="base_width" value="0.05" />
    <xacro:property name="base_length" value="0.05" />
    <xacro:property name="base_heigth" value="1.0" />

    <xacro:property name="cylinder_radius" value="0.3" />
    <xacro:property name="cylinder_length" value="0.03" />

    <xacro:property name="axle_offset" value="0.5" /> <!-- Space between joint and end of beam -->

    <link name = "base_footprint"/>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size = "${base_width} ${base_length} ${base_heigth}" />
            </geometry>
            <material name = "navy_blue" />
        </visual>
        <collision>
            <origin xyz = "0 0 0" rpy = "0 0 0" />
            <geometry>
                <box size = "${base_width} ${base_length} ${base_heigth}" />
            </geometry>
        </collision>
        <xacro:box_inertial m = "5.0" l = "${2*base_length}"
                                      w = "${2*base_width}"
                                      h = "${2*base_heigth}"
                                      xyz = "0 0 0"
                                      rpy = "0 0 0" />
    </link>

    <joint name="base_footprint_to_base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${base_heigth/2}" />
    </joint>

    <link name="platform">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius = "${cylinder_radius}" length = "${cylinder_length}" />
            </geometry>
            <material name = "orange" />
        </visual>
        <collision>
             <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <cylinder radius = "${cylinder_radius}" length = "${cylinder_length}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial m = "5.0" l = "${cylinder_length}"
                                      r = "${cylinder_radius}"
                                      xyz = "0 0 0"
                                      rpy = "0 0 0" />
    </link>


    <joint name="platform_to_base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="platform"/>
        <origin xyz="0 0 ${cylinder_length}" />
    </joint>


    <link name="mid_link">
        <visual>
            <origin xyz="0 0 ${base_heigth/4}" rpy= "0 0 0"/>
            <geometry>
                <box size = "${base_width} ${base_length} ${base_heigth/2}" />
            </geometry>
            <material name = "yellow" />
        </visual>
        <collision>
            <origin xyz = "0 0 ${base_heigth/4}" rpy = "0 0 0" />
            <geometry>
                <box size = "${base_width} ${base_length} ${base_heigth/2}" />
            </geometry>
        </collision>
        <xacro:box_inertial m = "2.0" l = "${base_length}"
                                      w = "${base_width}"
                                      h = "${base_heigth/2}"
                                      xyz = "0 0 0"
                                      rpy = "0 0 ${base_heigth/4}" />
    </link>

    <joint name="base_to_mid_joint" type="revolute">
        <parent link="base_link"/>
        <child link="mid_link"/>
        <origin xyz="0 ${base_width} ${base_heigth - axle_offset}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14" />
  </joint>

    <link name="top_link">
        <visual>
            <origin xyz="0 0 ${base_heigth/4}" rpy= "0 0 0"/>
            <geometry>
                <box size = "${base_width} ${base_length} ${base_heigth/2}" />
            </geometry>
            <material name = "red" />
        </visual>
        <collision>
            <origin xyz = "0 0 ${base_heigth/4}" rpy = "0 0 0" />
            <geometry>
                <box size = "${base_width} ${base_length} ${base_heigth/2}" />
            </geometry>
        </collision>
        <xacro:box_inertial m = "2.0" l = "${base_length}"
                                      w = "${base_width}"
                                      h = "${base_heigth/2}"
                                      xyz = "0 0 0"
                                      rpy = "0 0 ${base_heigth/4}" />
    </link>

    <joint name="mid_to_top_joint" type="revolute">
        <parent link="mid_link"/>
        <child link="top_link"/>
        <origin xyz="0 ${base_width} ${base_heigth - axle_offset}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="100.0" velocity="0.5" lower="-3.14" upper="3.14" />
  </joint>

   
</robot>
